community_list = [
  [ "Avon", "Hartford", "http://www.town.avon.ct.us/Public_Documents/index" ],
  [ "Berlin", "Hartford", "http://www.town.berlin.ct.us/" ],
  [ "Bloomfield", "Hartford", "http://www.bloomfieldct.org/Plugs/home.aspx" ],
  [ "Bristol", "Hartford", "http://www.ci.bristol.ct.us/" ],
  [ "Burlington", "Hartford", "http://burlingtonct.us/" ],
  [ "Canton", "Hartford", "http://www.townofcantonct.org/" ],
  [ "East Granby", "Hartford", "http://www.eastgranbyct.org/" ],
  [ "East Hartford", "Hartford" ],
  [ "East Windsor", "Hartford" ],
  [ "Enfield", "Hartford" ],
  [ "Farmington", "Hartford", "http://www.farmington-ct.org/" ],
  [ "Glastonbury", "Hartford", "http://www.glasct.org/" ],
  [ "Granby", "Hartford", "http://www.granby-ct.gov/Public_Documents/index" ],
  [ "Hartford", "Hartford" ],
  [ "Hartland", "Hartford", "http://www.munic.state.ct.us/HARTLAND/GeneralInfo.htm" ],
  [ "Manchester", "Hartford", "http://www.townofmanchester.org/" ],
  [ "Marlborough", "Hartford", "http://www.marlboroughct.net/" ],
  [ "Newington", "Hartford", "http://www.newingtonct.gov/" ],
  [ "Plainville", "Hartford" ],
  [ "Rocky Hill", "Hartford", "http://www.rockyhillct.gov/" ],
  [ "Simsbury", "Hartford", "http://www.simsbury-ct.gov/" ],
  [ "Southington", "Hartford", "http://www.southington.org/" ],
  [ "South Windsor", "Hartford", "http://www.southwindsor.org/Pages/index" ],
  [ "Suffield", "Hartford", "http://www.suffieldtownhall.com/" ],
  [ "West Hartford", "Hartford", "http://www.west-hartford.com/" ],
  [ "Wethersfield", "Hartford", "http://wethersfieldct.com/" ],
  [ "Windsor", "Hartford", "http://www.townofwindsorct.com/" ],
  [ "Windsor Locks", "Hartford", "http://www.windsorlocksct.org/" ],
 
  [ "Andover", "Tolland", "http://andoverconnecticut.org/" ],
  [ "Bolton", "Tolland", "http://www.bolton.govoffice.com/" ],
  [ "Columbia", "Tolland", "http://www.columbiact.org/" ],
  [ "Coventry", "Tolland", "http://www.coventryct.org/" ],
  [ "Ellington", "Tolland", "http://www.ellington-ct.gov/Plugs/homepage.aspx" ],
  [ "Hebron", "Tolland", "http://www.hebronct.com/" ],
  [ "Mansfield", "Tolland", "http://www.mansfieldct.gov/" ],
  [ "Somers", "Tolland", "http://www.somersct.gov/" ],
  [ "Stafford", "Tolland", "http://www.staffordct.org/index.php" ],
  [ "Tolland", "Tolland", "http://www.tolland.org/" ],
  [ "Union", "Tolland", "http://www.unionconnecticut.org/" ],
  [ "Vernon", "Tolland", "http://www.vernon-ct.gov/town-hall" ],
  [ "Willington", "Tolland", "http://www.willingtonct.org/public_documents/willingtonct_townclerk/townclerk2" ],

  [ "Chester", "Middlesex" ],
  [ "Clinton", "Middlesex" ],
  [ "Cromwell", "Middlesex", "http://www.cromwellct.com/" ],
  [ "Deep River", "Middlesex" ],
  [ "Durham", "Middlesex" ],
  [ "East Haddam", "Middlesex" ],
  [ "East Hampton", "Middlesex" ],
  [ "Haddam", "Middlesex" ],
  [ "Killingworth", "Middlesex" ],
  [ "Middlefield", "Middlesex" ],
  [ "Middletown", "Middlesex", "http://www.cityofmiddletown.com/" ],
  [ "Old Saybrook", "Middlesex" ],
  [ "Portland", "Middlesex", "http://www.portlandct.org/" ],
  [ "Westbrook", "Middlesex" ],

  [ "Barkhamsted", "Litchfield", "http://barkhamsted.us/Home/tabid/36/Default.aspx" ],
  [ "Bethlehem", "Litchfield" ],
  [ "Bridgewater", "Litchfield" ],
  [ "Canaan", "Litchfield" ],
  [ "Colebrook", "Litchfield" ],
  [ "Cornwall", "Litchfield" ],
  [ "Goshen", "Litchfield" ],
  [ "Harwinton", "Litchfield" ],
  [ "Kent", "Litchfield" ],
  [ "Litchfield", "Litchfield" ],
  [ "Morris", "Litchfield" ],
  [ "New Hartford", "Litchfield", "http://www.town.new-hartford.ct.us/" ],
  [ "New Milford", "Litchfield" ],
  [ "Norfolk", "Litchfield" ],
  [ "North Canaan", "Litchfield" ],
  [ "Plymouth", "Litchfield" ],
  [ "Roxbury", "Litchfield" ],
  [ "Salisbury", "Litchfield" ],
  [ "Sharon", "Litchfield" ],
  [ "Thomaston", "Litchfield" ],
  [ "Torrington", "Litchfield" ],
  [ "Warren", "Litchfield" ],
  [ "Washington", "Litchfield" ],
  [ "Watertown", "Litchfield" ],
  [ "Winchester", "Litchfield" ],
  [ "Woodbury", "Litchfield" ]
]

community_list.each do |city, county, townhall_link|
  Community.create( city: city, county: county, townhall_link: townhall_link)
end

